name: premier-taco-dmc
channels:
  - defaults
dependencies:
  - python=3.8 #done
  - pip=21.1.3 #done
  - numpy=1.19.2 #done
  - absl-py=0.13.0 #done
  - pyparsing=2.4.7 #done
  - jupyterlab=3.0.14 #done
  - scikit-image=0.18.1 #done
  - nvidia::cudatoolkit=11.1 
  - pytorch::pytorch
  - pytorch::torchvision
  - pytorch::torchaudio
  - pip:
    - chardet
    - gym
    - termcolor==1.1.0
    - dm_control
    - tb-nightly
    - imageio==2.9.0
    - imageio-ffmpeg==0.4.4
    - hydra-core==1.1.0
    - hydra-submitit-launcher==1.1.5
    - pandas==1.3.0 #done
    - ipdb==0.13.9
    - yapf==0.31.0
    - mujoco_py==2.0.2.13
    - sklearn==0.0
    - matplotlib==3.4.2
    - opencv-python==4.5.3.56